pulp-platform/carfield

- Bender.lock
- Bender.yml
- Makefile
- hw/carfield_pkg.sv
* Set Cheshire's `CieOnTop=1`
* Extend cacheable, idempotent, executable (CIE) region length to cover shared L2 space (`[0x7800_0000, 0x78400_0000]`):
* **External Non-CIE**: `[0x2000_0000, 0x7000_0000)`
* **External CIE**: `[0x7000_0000, 0x8000_0000)`
> Add Code Execution from shared L2

- Bender.lock
- Bender.yml
- hw/carfield.sv
- hw/carfield_pkg.sv
* Remove behavioral string parameters: use combinational ROM and OTP
Fixes #26
> hw: Bump security island

- Bender.local
- Bender.lock
- Bender.yml
- Makefile
- hw/carfield.sv
force push :smiley: ) @yvantor
> Bump main IPs

- Bender.lock
- Bender.yml
- hw/carfield.sv
> Update security island reset interface

- Bender.local
- Bender.lock
- Bender.yml
Updating safety island and register interface.
> Update main IPs

- Makefile
- hw/carfield.sv
- hw/l2_wrap.sv
- sw/.gitignore
* hw: Fix missing signal declaration for l2 reset
* hw: Fix 'declaration initial assignment' is not supported in synth
* Makefile: Initialize cockpit in nonfree
> Various minor fixes

- Bender.lock
- Bender.yml
- hw/carfield_pkg.sv
- sw/tests/hostd/system_timer_test.c
* Fix Linux flow ([PLIC HW bug](https://github.com/pulp-platform/opentitan_peripherals/pull/7))
* Add end-to-end Linux boot flow
* Use ID remapper serializer for CVA6
> Bump Cheshire dependency

- Bender.lock
- Bender.yml
* Fix latch caught by synthesis
> Bump hyperbus dependency

- bender-common.mk
@alex96295 @luca-valente could you approve please?
> Fixed typo in bender-common.mk.

- hw/carfield.sv
- hw/carfield_pkg.sv
Shifting PULP base address according with cluster index to fix addressability.
> Fix for PULP cluster addressability.

- Bender.lock
- Bender.yml
I've added some spill register in L2 mem for better timing
> Add AXI cut to L2 memory for improved timing

- Bender.local
- Bender.lock
- Bender.yml
- hw/carfield.sv
- hw/carfield_pkg.sv
- hw/cheshire_wrap.sv
- hw/hyperbus_wrap.sv
- hw/l2_wrap.sv
* Bump AXI to expose number of synch registers in AXI CDC from FIFOs
* Propagate said parameter in carfield
* Bump IPs to expose said parameter
> Propagate sync register parameter for CDC FIFOs

- Bender.yml
- carfield.mk
- hw/carfield.sv
- sw/tests/bare-metal/safed/sw.mk
- tb/carfield_fix.sv
- tb/carfield_tb.sv
- tb/vip_security_island_soc.sv
* Add `vip_security_island.sv` module for verification
* Cleanup makefrags
* Connect missing port in `lossy_valid_to_stream` module
> Various updates - 4

- Bender.local
- Bender.lock
- Bender.yml
Packs Valid/Dirty SRAMs for multicore
> cheshire: Bump cva6 pulp-v0.4.3

- carfield.mk
- sw/sw.mk
We add the [`mibench`](https://github.com/alex96295/mibench) benchmark suite to the set of available tests for carfield
> Add mibench automotive benchmark compilation flow

- Bender.lock
- Bender.yml
* Change DQ and RWDS tri-state enable signals before data, relaxing timing through the OE pin
> Bender.yml: Bump hyperbus

- hw/carfield.sv
This PR adds a DEFINE to select Cheshire RTL or netlist
> Add define to select Cheshire RTL or netlist

- Bender.lock
- Bender.yml
- hw/hyperbus_wrap.sv
* Expose sync stages for CDC in hyperbus top
> Bump hyperbus to latest version

- Bender.local
- Bender.lock
- Bender.yml
* Mismatched FPU package in cv32 in safety island was causing test to fail
> Bump Safety Island to fix FPU bug

- hw/carfield_pkg.sv
* The IP is not used in carfield
> hw: Disable VGA

- Bender.local
* Fix byte enable assignment in `tc_sram_xilinx`
> Bender.local: Point to latest release of `tech_cells_generic`

- hw/carfield.sv
- tb/vip_carfield_soc.sv
This PR adds one DEFINE to select the INT_CLUSTER netlist and one DEFINE to provide a path to HYP_SDF
> Add one DEFINE to select INT_CLUSTER netlist and one DEFINE to provide a path to HYP_SDF

- Bender.local
- Bender.lock
- Bender.yml
> Bender: Bump cheshire

- carfield.mk
* Speedup CI by triggering FPGA implementation on main only
> carfield.mk: Speedup CI by triggering FPGA implementation on main only

- Bender.lock
- Bender.yml
- hw/carfield.sv
- hw/carfield_pkg.sv
Bumping integer cluster to the latest updated version.
> Bump integer cluster

- Bender.lock
- Bender.yml
Bump cluster commit to fix CSR assignment that breaks FPGA imlementation.
> Fix FPGA implementation

- Bender.lock
- Bender.yml
- hw/carfield_pkg.sv
Port Cheshire with LLC partitioning functionality and tagger to carfield.
> Add HW partitioning feature to LLC

- Bender.lock
- Bender.yml
- carfield.mk
- hw/carfield.sv
- sw/tests/bare-metal/hostd/mbox_test.c
Bumped SECD repo:
- Including techn dependent clk_mux2, clk_div, clk_inv
- Mailbox test aligned to new mailbox
Fixed mailbox test CVA6 side
Modified Carfield top module with defines for PLS
>  [SECD] Bump SECD & fix mailbox test

- Bender.local
- Bender.lock
* Set FULL_BW=1 to optimize for speed
> Bender: Bump axi_riscv_atomics to v0.8.2

- hw/carfield.sv
This reverts commit 03d3ae34e31e33ec6c923370d02b54051e93b17a.
> Revert "hw: Fix localparam array direction"

- Bender.lock
- Bender.yml
* Add AXI FIFO to increase number of outstanding transactions
> Bender: Bump hyperbus to latest version

- Bender.lock
- Bender.yml
Fix error at input/output interface with flash and otp signals.
> [SECD] Bump OpenTitan

- tb/vip_carfield_soc.sv
This PR fixes a bug in the PATH_TO_HYP_SDF assignment
> Fix PATH_TO_HYP_SDF assignment

- Bender.lock
- Bender.yml
- Removing reset synchronizer
- Updating bootrom parameter: now loading from SPI flash until the emulated flash if completely filled (32k word out of 
32k). It was loading only 5k words before.
> Bump opentitan

- Bender.lock
- Bender.yml
Updating bootrom: spi freq now 5MHz.
> [SECD] Bump SECD

- carfield.mk
[* Split manual and scheduled job for secure boot](https://iis-git.ee.ethz.ch/carfield/carfield-nonfree/-/merge_requests/39)
> carfield.mk: Split between manual and scheduled job for secure boot

- scripts/elf2header.py
- scripts/elf2slm.py
- sw/tests/bare-metal/pulpd/sw.mk
- tb/carfield_tb.sv
This PR reverts the changes made in the python scripts that generate the offloading stimuli to fix the RTL offloading simulations.
> Fix RTL offloading tests

- .gitlab-ci.yml
- carfield.mk
- Pass pipeline source to child
- Bump carfield-nonfree
> ci: Run litmus tests on scheduled pipelines

- Bender.lock
- Bender.yml
* Fix bug in perf counters when no events present
> Bender: Bump cheshire and cva6

- Bender.lock
- Bender.yml
Added new test suitable for PLS. It performs writes to 30 consecutive L2 and L3 addresses and reads them back expecting the written value.
> [SW] Bump SECD, added new test

- .github/workflows/lint.yml
- carfield.mk
- sw/.clang-format
- sw/.gitignore
- sw/include/bits.h
- sw/include/car_memory_map.h
- sw/include/car_util.h
- sw/include/regs/irq_router.h
- sw/tests/bare-metal/hostd/irq_router_rw.c
- tb/carfield_tb.sv
Adds basic test for configuring the `irq_router`
> Add test for irq_router

- sw/include/car_memory_map.h
- sw/include/regs/axi_llc_regs.h
- sw/tests/bare-metal/hostd/cache_partitioning_basic.c
Checks if we can access the cache partitioning configuration registers. This is just a basic integration test.
> Add test for cache partitioning

- .gitignore
- sw/tests/bare-metal/hostd/minimal.c
Useful for post-layout and just plain old sanity checking
> Add minimal test

- carfield.mk
This PR is linked to [!43](https://iis-git.ee.ethz.ch/carfield/carfield-nonfree/-/merge_requests/43).
> Add more offload regressions  for PULP.

- Bender.lock
- Bender.yml
New SPI frequency @ boot: 50MHz
> [SECD] Bumping OT: changed SPI frequency setup in bootrom code

- Bender.lock
- Bender.yml
* Make xnxti opt-in on core side
> Bender: Bump safety island

- hw/carfield.sv
* Helps timing when using hierarchical approach with black-boxed macros, since a FF is immediately available as sync point after the cheshire macro
> hw: Add slice before mailbox unit's atomic adapter

- tb/carfield_tb.sv
Can be used by passing appropriate simulator args like e.g. this
```
common_defs += -DCHS_LLC_MACRO_HIER\(NUM\)=tb_carfield_soc.fix.i_dut.i_cheshire_wrap.i_cheshire_soc.gen_llc_i_llc.i_axi_llc_top_raw.i_llc_ways.gen_data_ways_\`\`NUM\`\`__i_data_way.i_data_sram.i_data_sram.gen_2048w_64dw_8be_sram_bank_2048w_64dw.[...].DATA_ARRAY
```
> tb: Add randomized memory initialization option for cheshire

- Bender.lock
- Bender.yml
* Fix chip select signal released too early with cfg register
> Bender: Bump hyperbus

- Bender.local
- Bender.lock
- Bender.yml
* Remove non-resettable FF in debug ROM
> Bump debug module

- Bender.lock
- Bender.yml
> Bender: Bump cheshire to use open-source tagger

- README.md
- docs/gs.md
- docs/tg/index.md
- docs/tg/sim.md
- docs/tg/xilinx.md
- mkdocs.yml
Added FPGA related docs.
Note that what was before in the front page has been moved to tg/sim.md and gs.md
> docs: Added FPGA

- carfield.mk
- target/.gitignore
Leftover bugs after tree/command refactoring
> treewide: Fix litmus and secure boot tests

- Bender.yml
- target/xilinx/flavor_bd/flavor_bd.mk
- target/xilinx/flavor_vanilla/constraints/carfield_top_xilinx.xdc
- target/xilinx/flavor_vanilla/flavor_vanilla.mk
- target/xilinx/scripts/overrides.sh
- target/xilinx/src/overrides/tc_clk_xilinx.sv
This is the same [`ck/cfg_top_fpga_fix`](https://github.com/pulp-platform/carfield/tree/ck/cfg_top_fpga_fix) branch but rebased on top of the target `yt/cfg_top`.
> Fix FPGA implementation flow.

- carfield.mk
- scripts/elf2header.py
- sw/sw.mk
- sw/tests/bare-metal/hostd/pulp-offload-intf.c
- sw/tests/bare-metal/hostd/pulpd_offloader_blocking.c
I closed #255 and opened this one, rebased on the main branch, and the previous comments addressed.
> Add pulp-offload-intf.c to stimulate and test CVA6-PULP cluster interference

- carfield.mk
* Add `.venv` to build artifacts
> carfield.mk: Bump `nonfree`

- Bender.local
- Bender.lock
- carfield.mk
This PR goes with the following MR:
https://iis-git.ee.ethz.ch/carfield/carfield-nonfree/-/merge_requests/55
> ci: Add file logging, and correct ethernet address parsing for FPGAs
