.gitignore, Bender.local, Bender.lock, Bender.yml
Reference FPU version: [pulp-v0.1.1](https://github.com/pulp-platform/cvfpu/releases/tag/pulp-v0.1.1)
* Alignment required for:
* Once aligned:
=> Align FPU version for carfield

Bender.local, Bender.lock, Bender.yml, Makefile, bender-common.mk, bender-synth.mk, hw/carfield.sv, hw/carfield_pkg.sv, scripts/Makefile, scripts/spyglass/scripts/run_lint.tcl, scripts/spyglass/sgdc/func.sgdc, scripts/spyglass/src/carfield_wrap.sv
**[Comment @mp-17]** This is a good starting point for elaboration. If we want to extend the checks to the CDCs and add reliability to the design, we have to modify the `.sdc` constraints -> to be addressed in a separate PR.
* Bump integer cluster pointer (fix `mchan` DMA width mismatches [[1]](https://github.com/pulp-platform/pulp_cluster/commits/yt/carfield-integration))
* Fix `reg_to_tlul` timing loop in register interface [[2]](https://github.com/pulp-platform/register_interface/pull/38))
* Bump Open Titan to solve redefinition of `packages` and `macros`
* Fix Bender targets
* Waive linting for `line-length` check in macro definition, it is not understood by the synthesis tool
=> Fix RTL against Spyglass and Synthesis (elaboration)

Bender.local, Bender.lock, Bender.yml, Makefile, hw/carfield.sv
* Connecting Safety Island's  `pwr_on_rst_ni` temporarily to global reset.
* Updating non-free commit to elide spyglass since we cannot reliably use it.
=> Fix Safety Island's power on reset connection and eliding Spyglass.

Bender.lock, Bender.yml, hw/carfield.sv
This PR:
* Bumps PULP cluster commit to the one updated with the new reset scheme;
* Extends the integer_cluster instance with the `pwr_on_rst_ni` and the `mbox_irq_i` signals.
=> Add power-on reset and mailbox interrupt to integer cluster

Bender.lock, Bender.yml, hw/carfield.sv
Here you can fid the reset strategy updates on the spatz cluster.
It automatically generates the wrapper with the interface you can see in carfield.sv
The power_on reset is probed to the isolate and the CDCs.
The reset_ni goes internally to the cluster and it is synchronized with its interrupts.
=> Update floating-point cluster reset interface 

.github/workflows/gitlab-ci.yml, Makefile
* Add synthesis flow up to compilation (excluded). Top level is `carfield` in `carfield.sv`.
It includes:
1. Analyze
2. Elaborate
3. Link
4. Timing loop check
* The job fails when there is an `Error` in one of the reports, or when a `timing loop` is detected.
* The job is ~30min, which is affordable
=> Add synthesis flow steps to carfield CI flow

hw/carfield.sv, hw/carfield_pkg.sv, hw/l2_wrap.sv, hw/regs/carfield_reg_pkg.sv, hw/regs/carfield_reg_top.sv, hw/regs/carfield_regs.csv, hw/regs/carfield_regs.hjson
Modify L2_wrap to align with the SoC reset scheme.
=> Update shared L2 reset strategy

Bender.lock, Bender.yml, hw/carfield.sv, hw/l2_wrap.sv, sw/tests/hostd/system_timer_test.c
Expose extra parameters to config the `axi_riscv_atomics_structs`. They default to Cheshire, which is fine for now.
Fixes #39
=> Add atomics support to shared L2 memory

hw/carfield.sv, target/synth/carfield_synth_wrap.sv, tb/carfield_fix.sv
The hyperbus peripheral is currently receiving its clock from an external port (which is not connected in carfield_chip at the moment!). However, the interfaces are supposed to be synchronous to the peripheral clock. Therefore this PR removes those external ports and connects the hyperbus peripheral to the peripheral clock domain/reset domain.
=> Properly connect the hyperbus peripheral to the right clock domain

Bender.lock, Bender.yml, carfield.mk, hw/carfield.sv, hw/carfield_pkg.sv, hw/cheshire_wrap.sv
Most updates have been performed in [cheshire](https://github.com/pulp-platform/cheshire), PR#31. It can be found at [this link](https://github.com/pulp-platform/cheshire/pull/31).
=> Wire interrupts in Carfield

hw/carfield.sv
=> Fix host clock and reset in edge propagators for safety island interrupts

Bender.lock, Bender.yml, sw/tests/hostd/mbox_test.c, tb/carfield_fix.sv, tb/carfield_tb.sv
**[Security island]**
**[Carfield]**
=> treewide: Bump security island dependency

Bender.yml
A module was removed in the nonfree repository, hence we remove it from here as well.
=> Bender.yml: Remove entry from nonfree list

Bender.lock, Bender.yml, hw/cfg/spatz_carfield.hjson
* Add new and fix existing SW tests
* Fix undriven nets
* Fix race condition between vector store and load
* Decouple scatter-gather index width from SEW
* Fix hazard detection of indexed memory operations
* Propagate testmode signal
=> Bender: Bump spatz

hw/carfield.sv
Mailboxes are in the same clock and reset domain of the host, and they do not require isolate signals
=> hw: Fix out of bounds array

Bender.lock, Bender.yml
This PR bumps Spatz to the latest version, fixing some timing issues:
* [Remove register_offload_req parameter](https://iis-git.ee.ethz.ch/spatz/spatz/-/commit/caacaf5f3fdc9b265bedf506ac1597af318e9fc0)
* [Pipeline the core response](https://iis-git.ee.ethz.ch/spatz/spatz/-/commit/24c3968564c06d460cda12d514d9114f28d52da3)
* [Add the dp-fdotp kernel](https://iis-git.ee.ethz.ch/spatz/spatz/-/commit/4d3edc29d76dfea5af4dd562d29f64ee07e90520)
* [Add the dp-faxpy kernel](https://iis-git.ee.ethz.ch/spatz/spatz/-/commit/d9138f1dd271b12a34a670416e925cf25efac1a6)
=> Bump Spatz to version

Bender.local, Bender.lock, CHANGELOG_WEEKLY.md, target/xilinx/scripts/run.tcl
* Bump FPU to `pulp-v0.1.3` (forced in `Bender.local`)
* Align AXI to proper (latest) version `v0.39.0`
* Temporary remove FPGA timing check from CI
=> Various updates - 2

Bender.lock, Bender.yml, carfield.mk, hw/carfield.sv, hw/carfield_pkg.sv
Add a second self-invalidation-coherent cva6 core. Tasks:
=> cheshire_cfg: Set number of cores to 2

tb/carfield_fix.sv, tb/vip_carfield_soc.sv
The signal is active low (convention: `*_n` or `*n` in the signal name), but the corresponding I/O pad (bidirectional) was not following said convention.
=> Rename incorrect hyperbus reset bidirectional IO signal

README.md, carfield.mk, hw/carfield.sv, tb/carfield_fix.sv, tb/vip_security_island_soc.sv
Adds (experimental) secure boot mode as pin. This feature make sure that the security island comes up at the roughly the same time as the cva6 and can't be clockgates/isolated. In summary this should allow a secure boot flow to be implemented in software
=> Add secure boot pin

Bender.lock, Bender.yml, carfield.mk, hw/carfield_pkg.sv
=> Bender: Bump `axi_rt` AXI real-time unit

Bender.local, Bender.lock, Bender.yml, bender-common.mk, hw/carfield.sv, hw/carfield_pkg.sv
=> Bender: Bump `pulp_cluster` dependency

Bender.lock, Bender.yml
In this PR, we point to the open-source upstream of:
=> Point to open-source deps - 1

carfield.mk
Required by cheshire. This fixes the current re-initialisation of the dependencies with every make command, since `.chs_deps` can now be created (e.g. [here](https://iis-git.ee.ethz.ch/github-mirror/carfield/-/jobs/739933#L2949) this failed)
=> carfield.mk: Set bender root

README.md, carfield.mk, scripts/start_carfield.tcl
The three-step flow is the recommended flow by questa. It provides more control and avoids re-optimising the design for each run. This is particularly critical for highly parallel simulations, since only one questa instance can run vopt at any time.
Note that this also removes accessibility default and logging by default for reduced CI footprint. Full accessibility, logging, and the gui can be activatied by setting `DEBUG=1`.
=> Makefile/questa: Switch to three-step flow

Bender.lock, Bender.yml, tb/carfield_tb.sv
see https://github.com/pulp-platform/cheshire/pull/67.
This lets the testbench defer termination until there is no active UART transmission.
=> carfield_tb: Wait for UART before terminating sim

carfield.mk, sw/sw.mk
Add make targets to run and evaluate the litmus tests on carfield. Furthermore, add an optional job to run the litmus tests to the nonfree CI. _Note: https://github.com/pulp-platform/bender/pull/135, a bender release + update on the IIS machines are required for the litmus CI to pass._
=> ci: Add litmus tests

Bender.local, Bender.lock, Bender.yml, bender-synth.mk, carfield.mk, hw/carfield.sv, hw/carfield_pkg.sv
**Note:** This version of the ethernet IP **does not** rely on a DMA to stream data to the shared scratchpad memory (in carfield, L2), and uses large buffering local to the IP. 
@mp-17 Before merging, have a look at the additional memory cuts (8 in total). Elaboration of `carfield_soc` passes, so the cuts are linked properly. I am tagging you to make you aware of the additions and the need to update the FP
=> Integrate Ethernet IP

Bender.local, Bender.lock, Bender.yml
* `cheshire` (main branch, `4fbb6b0`)
* `idma` (`v0.5.1`) -> Fixes non-synthesizable syntax
* `unbent` (`v0.1.5`)
* `tech_cells_generic` (`v0.2.13`)
* `irq_router` (`v0.0.1-beta.1`)
=> Bender: Bump various IPs

.gitignore, carfield.mk, hw/carfield.sv, hw/regs/carfield_reg_top.sv, hw/regs/carfield_regs.csv, hw/regs/carfield_regs.hjson, sw/include/car_util.h, sw/tests/bare-metal/hostd/addressability_test.c, sw/tests/bare-metal/hostd/helloworld.c, sw/tests/bare-metal/hostd/pulp-offload.c, sw/tests/bare-metal/hostd/safed_offloader_blocking.c, sw/tests/bare-metal/hostd/sw_rst_seq.c, sw/tests/bare-metal/hostd/system_timer_test.c, tb/carfield_tb.sv
**[EDIT]** @alex96295:
Fixes #71  
Fixes #126 
Fixes #46
=> Clock gate and isolate Islands on reset

Bender.lock, Bender.yml, carfield.mk
In this PR, we bump to open source version of spatz
=> Point to open source deps - 3

tb/carfield_fix.sv, tb/carfield_tb.sv
* Aligning RTC, System clock, and JTAG clock with values in chip-level testbench;
* Insert Hyperbus' max burst time config in testbenchl.
=> Align boundary conditions with chip-level repo

hw/carfield.sv, hw/carfield_pkg.sv
* Until BE is clean; the instantiation is enabled by setting `IslandsCfg.EnEthernet = 1`
=> Parameterize ethernet instantiation and disable by default

hw/carfield.sv, hw/carfield_pkg.sv
* We make the default value of clock dividers controlling the clock of each domain parameterizable. 
* Change the value in `carfield_pkg.sv` to have a different clock div value after PoR
* At runtime, the divider value is configurable
=> Parameterize default clock divider integer value for domains 

Bender.lock, Bender.yml
Update SECD: adding a clk buffer in output of clk divider of SPI, to guarantee the constraints to be associated to a tech cell correctly.
=> [SECD] Bump OpenTitan

hw/regs/carfield_reg_top.sv, hw/regs/carfield_regs.csv, hw/regs/carfield_regs.hjson
* After PoR, when the chip receives host, alt and periph clock, the multiplexer for the L2 domain was set to distribute host clock by default. But L2 is supposed to work in alt clock domain by default. This can be changed dynamically during runtime
=> hw: Change clk mux default value after PoR for L2 domain

hw/cheshire_wrap.sv
* The for loop was iterating on the number of synchrnous interfaces instead of asyncrhonous, with the former set to 1. Hence, only one reg cdc for port 0 was generated!
=> hw: Fix instantiation of reg cdc for external reg interface

tb/carfield_fix.sv
Do not wait for OT to boot if `secure_boot` is deasserted. Lets TB terminate for test cases that do not initialise OT.
=> carfield_fix: Skip OT boot if no secure boot

Bender.local, Bender.lock, Bender.yml
The PR provides:
* Replace latches in rapid recovery RF with FFs
* Bumps of the PULP cluster commits to kill the critical path in the DMR checkers (fixes time violations in synthesis, should fix it also in P&R, which is running at the moment)
* Bumps of the PULP cluster commits to try and fix the post-synthesis/layout simulations of the PULP cluster by using a structures-based AXI crossbar instead of the one using interfaces (this could be the reason why only AXI indeces are swapped in synthesis, but the address map is not changed accordingly)
* A lot of repetitive commits that must be properly squashed :)
=> Bump PULP cluster to fix macro implementation

Bender.lock, Bender.yml, carfield.mk
- Updated bootrom code for SECD: now loading into emulated flash only 7/8 of the whole memory than before due to the 
absence of the last 8th bank of emulated flash.
- Fixed SPI frequency to 1/20 of input frequency (@100MHz input clk, SPI clk is 5MHz)
=> [SECD] Bump SECD

Bender.lock, Bender.yml
This PR is bumping PULP cluster for fixes to inconsistent rtl code.
The PULP cluster commit in this branch resulted in clean setup/hold timing reports with P&R closing at 500 MHz.
=> Bumping PULP cluster for code cleanup.

hw/carfield.sv
* Tie unused signals when ethernet is disabled
* Fix connection for spatz timer interrupt
=> hw: Minor fixes to carfield top

Bender.local, Bender.lock, Bender.yml
Bumping:
* RISCY to backup PC coming directly from IF to make redundant grouping work with rapid recovery.
* Redundancy cells to backup IF PC when cores are in independent mode.
* PULP cluster accordingly with the above ones.
=> Update Integer cluster dependencies

sw/tests/bare-metal/hostd/system_timer_test.c
* Periph domain always on, enabling other islands not needed
=> sw: Remove init function from timer test

Bender.local, Bender.lock, Bender.yml
* Bits tracking core errors were flipped in endianness, so that error counters index was not matching the corresponding core
=> Bender: Fix TCLS endianness in safety island

Bender.lock, Bender.yml, hw/l2_wrap.sv
In this PR, we bump to open source version of the (shared) dynamic scratchpad memory
=> Point to open-source deps - 2

Bender.lock, Bender.yml
* Point to open source `safety-island`
* This completes the open-sourcing process
Fixes #238
=> bender: Point to open-source safety-island IP

carfield.mk, docs/gs.md, requirements.txt
Spatz hw generation python scripts rely on two additional dependencies (_jsonref_, _jsonschema_) not listed in [requirements.txt](https://github.com/pulp-platform/carfield/blob/main/requirements.txt).
Moreover, the Spatz makefile will default to python3.6 if the PYTHON variable is not set. Therefore, changed it in [carfield.mk](https://github.com/pulp-platform/carfield/blob/main/carfield.mk) to default to python3.
Finally, remove the duplicated _hjson_ dependency.
=> Fix Spatz python dependencies in Carfield top level

carfield.mk
The CVA6 sdk was before selected via branch, creating issues with newer versions
See [CI merge request](https://iis-git.ee.ethz.ch/carfield/carfield-nonfree/-/merge_requests/49)
=> ci: Fix hash of CVA6 sdk

hw/carfield.sv
Fixing connections related to the parametrization of buses. In particular:
* [PcrsIdx](https://github.com/pulp-platform/carfield/blob/astral-fixup/hw/carfield.sv#L764) is introduced to prevent the registers' response bus to be X;
* [EccAsyncIdx](https://github.com/pulp-platform/carfield/blob/astral-fixup/hw/carfield.sv#L1137) is introduced to resolve a questa warning;
* Some reg2hw connections were reshuffled to either connect some (see spatz_busy.de that always remained floating) or make them more logical.
=> Fixing regbus (a)synchronous parameters and rearranging connections.

Bender.lock, Bender.yml, hw/carfield.sv, hw/cheshire_wrap.sv
=> Moved dedicated AXI ID remappers into PULP cluster

Bender.lock, Bender.yml
Add Spatz FF-based vregfile when targeting FPGA https://github.com/pulp-platform/spatz/pull/17
=> fpga: Update spatz hash to support FPGA

Bender.lock, Bender.yml, bender-sim.mk, carfield.mk, target/.gitignore, target/sim/sim.mk, target/sim/src/vip_carfield_soc.sv
* Re-use existing code in hyperbus to fetch sv model of HyperRAM and SDF
* Fix download of Hyperbus models
* Add `-sdf` switch to `vopt` to inform the tool that a part of the design uses SDF
* Update SDF annotation in testbench following changes in HyperRAM instance model naming (from `dut` to `i_hyper`)
=> Update hyperbus and de-duplicate HyperRAM model fetching

carfield.mk, requirements.txt
* Force usage of `venv`
* Add `venv` as order-only prerequisite where missing
=> Fix `venv` usage

carfield.mk
* On some machines, python calls may still fail if reference to venv is not explicit in the path (see our internal CI: https://iis-git.ee.ethz.ch/github-mirror/carfield/-/pipelines/99676)
=> carfield.mk: Use venv by default
